/**
 * DEEPER asset pipeline — original synthesized audio (WAV, 22050 Hz mono/16-bit).
 * Every sound is generated by this script; no downloaded or copyrighted audio.
 * Run: npm run audio
 * v1.2: extended machine-tier sonic differentiation, impact material differences,
 * hazard warning cues, environmental loops/transitions, deep-stratum ambience,
 * high-tier machine power feedback, WOW-beat payoff.
 */

import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import { mulberry } from "./pixutil";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const OUT = path.join(ROOT, "public", "assets", "audio");
const RATE = 22050;

function wav(samples: Float32Array): Buffer {
  const n = samples.length;
  const buf = Buffer.alloc(44 + n * 2);
  buf.write("RIFF", 0);
  buf.writeUInt32LE(36 + n * 2, 4);
  buf.write("WAVE", 8);
  buf.write("fmt ", 12);
  buf.writeUInt32LE(16, 16);
  buf.writeUInt16LE(1, 20);
  buf.writeUInt16LE(1, 22);
  buf.writeUInt32LE(RATE, 24);
  buf.writeUInt32LE(RATE * 2, 28);
  buf.writeUInt16LE(2, 32);
  buf.writeUInt16LE(16, 34);
  buf.write("data", 36);
  buf.writeUInt32LE(n * 2, 40);
  for (let i = 0; i < n; i++) {
    const v = Math.max(-1, Math.min(1, samples[i]));
    buf.writeInt16LE(Math.round(v * 32000), 44 + i * 2);
  }
  return buf;
}

class Synth {
  s = new Float32Array(0);
  rnd = mulberry(7);
  t = 0;
  dur(seconds: number) {
    const n = Math.ceil(seconds * RATE);
    const ns = new Float32Array(n);
    ns.set(this.s.subarray(0, Math.min(this.s.length, n)));
    this.s = ns;
    return this;
  }
  noise(at: number, dur: number, gain: number, f0: number, f1: number, q = 1) {
    const start = Math.floor(at * RATE);
    const len = Math.floor(dur * RATE);
    let lp = 0;
    for (let i = 0; i < len; i++) {
      const idx = start + i;
      if (idx >= this.s.length) break;
      const t = i / len;
      const f = f0 + (f1 - f0) * t;
      const white = this.rnd() * 2 - 1;
      lp += (white - lp) * Math.min(1, f / RATE * Math.PI * 2 * q);
      const env = Math.pow(1 - t, 1.6) * gain;
      this.s[idx] += lp * env * 0.7 + (white - lp) * env * 0.3;
    }
    return this;
  }
  tone(at: number, dur: number, gain: number, f0: number, f1?: number, wave: "sine" | "square" | "saw" | "tri" = "sine", decay = 3) {
    const start = Math.floor(at * RATE);
    const len = Math.floor(dur * RATE);
    let phase = 0;
    for (let i = 0; i < len; i++) {
      const idx = start + i;
      if (idx >= this.s.length) break;
      const t = i / len;
      const f = f0 + ((f1 ?? f0) - f0) * t;
      phase += f / RATE;
      const ph = phase % 1;
      let v: number;
      switch (wave) {
        case "square": v = ph < 0.5 ? 1 : -1; break;
        case "saw": v = ph * 2 - 1; break;
        case "tri": v = ph < 0.5 ? ph * 4 - 1 : 3 - ph * 4; break;
        default: v = Math.sin(ph * Math.PI * 2);
      }
      const env = Math.exp(-decay * t) * gain;
      this.s[idx] += v * env;
    }
    return this;
  }
  done(gain = 0.9): Float32Array {
    let peak = 0;
    for (const v of this.s) peak = Math.max(peak, Math.abs(v));
    const g = peak > 0 ? gain / peak : 1;
    for (let i = 0; i < this.s.length; i++) this.s[i] *= g;
    return this.s;
  }
}

function digSoft(): Float32Array {
  const s = new Synth(); s.dur(0.28);
  s.noise(0, 0.16, 0.9, 300, 160).tone(0, 0.1, 0.25, 130, 70, "tri", 8);
  s.noise(0.14, 0.1, 0.5, 220, 120);
  return s.done();
}
function digRock(): Float32Array {
  const s = new Synth(); s.dur(0.32);
  s.noise(0, 0.2, 0.9, 900, 300).tone(0, 0.14, 0.4, 190, 90, "square", 10);
  s.noise(0.16, 0.12, 0.6, 1400, 500);
  return s.done();
}
function digMetal(): Float32Array {
  const s = new Synth(); s.dur(0.3);
  s.tone(0, 0.22, 0.7, 620, 590, "square", 7);
  s.tone(0, 0.22, 0.4, 930, 900, "sine", 6);
  s.noise(0, 0.1, 0.7, 2400, 1200);
  return s.done();
}
function digConcrete(): Float32Array {
  const s = new Synth(); s.dur(0.3);
  s.noise(0, 0.18, 0.9, 700, 260).tone(0, 0.18, 0.5, 240, 120, "saw", 8);
  s.noise(0.12, 0.14, 0.5, 1800, 700);
  return s.done();
}
function digCrystal(): Float32Array {
  const s = new Synth(); s.dur(0.4);
  s.tone(0, 0.3, 0.6, 1180, 1400, "sine", 5);
  s.tone(0.02, 0.3, 0.4, 1770, 2100, "sine", 6);
  s.noise(0, 0.06, 0.4, 3200, 2400);
  return s.done();
}
function digWood(): Float32Array {
  const s = new Synth(); s.dur(0.26);
  s.tone(0, 0.12, 0.6, 210, 160, "square", 9);
  s.noise(0, 0.1, 0.6, 800, 350);
  return s.done();
}
function digHeavy(): Float32Array {
  const s = new Synth(); s.dur(0.4);
  s.tone(0, 0.3, 0.9, 90, 55, "sine", 5);
  s.noise(0, 0.2, 0.8, 500, 180);
  return s.done();
}
function hardFail(): Float32Array {
  const s = new Synth(); s.dur(0.24);
  s.tone(0, 0.18, 0.6, 340, 330, "square", 8);
  s.noise(0, 0.1, 0.4, 2000, 1000);
  s.tone(0.05, 0.16, 0.3, 500, 240, "saw", 6);
  return s.done();
}
function upgradeSfx(): Float32Array {
  const s = new Synth(); s.dur(0.9);
  s.tone(0, 0.2, 0.5, 260, 520, "square", 4);
  s.tone(0.18, 0.2, 0.5, 390, 780, "square", 4);
  s.tone(0.36, 0.5, 0.5, 520, 1040, "tri", 2.5);
  s.noise(0.36, 0.3, 0.2, 3000, 800);
  return s.done();
}
function pickupSfx(): Float32Array {
  const s = new Synth(); s.dur(0.16);
  s.tone(0, 0.08, 0.5, 700, 900, "tri", 6);
  s.tone(0.06, 0.08, 0.4, 1000, 1300, "tri", 6);
  return s.done();
}
function bigLoot(): Float32Array {
  const s = new Synth(); s.dur(0.7);
  for (let i = 0; i < 7; i++) s.tone(i * 0.05, 0.18, 0.4, 600 + i * 130, 900 + i * 150, "tri", 5);
  s.noise(0, 0.3, 0.3, 2600, 900);
  return s.done();
}
function cargoFull(): Float32Array {
  const s = new Synth(); s.dur(0.5);
  s.tone(0, 0.14, 0.6, 330, 300, "square", 6);
  s.tone(0.16, 0.14, 0.6, 280, 250, "square", 6);
  s.tone(0.32, 0.16, 0.6, 240, 200, "square", 6);
  return s.done();
}
function sellSfx(): Float32Array {
  const s = new Synth(); s.dur(0.8);
  s.tone(0, 0.5, 0.5, 1560, 1550, "sine", 4);
  s.tone(0, 0.5, 0.25, 2340, 2300, "sine", 5);
  s.noise(0.02, 0.06, 0.4, 3000, 2000);
  s.tone(0.25, 0.4, 0.35, 1980, 1900, "sine", 5);
  return s.done();
}
function explosion(): Float32Array {
  const s = new Synth(); s.dur(1.3);
  s.tone(0, 0.5, 1, 110, 38, "sine", 3.2);
  s.noise(0, 0.7, 1, 1400, 90, 1.4);
  s.noise(0.06, 0.4, 0.7, 500, 120);
  return s.done(0.98);
}
function igniteSfx(): Float32Array {
  const s = new Synth(); s.dur(0.5);
  s.noise(0, 0.4, 0.8, 900, 2400);
  s.tone(0.05, 0.3, 0.3, 160, 90, "tri", 5);
  return s.done();
}
function waterSfx(): Float32Array {
  const s = new Synth(); s.dur(0.6);
  s.noise(0, 0.5, 0.7, 500, 1500);
  s.noise(0.1, 0.3, 0.4, 1200, 2400);
  return s.done();
}
function steamSfx(): Float32Array {
  const s = new Synth(); s.dur(0.9);
  s.noise(0, 0.8, 0.9, 2600, 1400);
  s.noise(0.2, 0.5, 0.5, 1800, 3200);
  return s.done();
}
function magmaSfx(): Float32Array {
  const s = new Synth(); s.dur(1.0);
  s.tone(0, 0.9, 0.7, 70, 50, "sine", 2);
  s.noise(0, 0.8, 0.5, 300, 800);
  s.noise(0.3, 0.5, 0.4, 900, 300);
  return s.done();
}
function resonanceSfx(): Float32Array {
  const s = new Synth(); s.dur(1.6);
  s.tone(0, 1.2, 0.4, 880, 1760, "sine", 1.2);
  s.tone(0.1, 1.2, 0.3, 1320, 2640, "sine", 1.4);
  for (let i = 0; i < 10; i++) s.tone(0.15 + i * 0.09, 0.22, 0.3, 1500 + i * 240 + (i % 3) * 130, 1400 + i * 200, "sine", 5);
  return s.done(0.85);
}
function machineSfx(): Float32Array {
  const s = new Synth(); s.dur(0.7);
  s.tone(0, 0.2, 0.6, 180, 320, "saw", 4);
  s.tone(0.2, 0.2, 0.6, 240, 420, "saw", 4);
  s.tone(0.4, 0.25, 0.6, 300, 520, "saw", 3);
  s.noise(0, 0.6, 0.2, 400, 900);
  return s.done();
}
function baseAmb(): Float32Array {
  const s = new Synth(); s.dur(2.4);
  s.tone(0, 2.2, 0.4, 55, 54, "sine", 0.7);
  s.noise(0, 2.0, 0.14, 300, 220);
  s.tone(0.6, 0.9, 0.25, 110, 108, "tri", 1.5);
  return s.done(0.6);
}
function hurtSfx(): Float32Array {
  const s = new Synth(); s.dur(0.35);
  s.tone(0, 0.3, 0.8, 320, 130, "saw", 5);
  s.noise(0, 0.2, 0.6, 900, 300);
  return s.done();
}
function extractSfx(): Float32Array {
  const s = new Synth(); s.dur(1.8);
  s.tone(0, 0.3, 0.5, 520, 490, "square", 2.5);
  s.tone(0.45, 0.3, 0.5, 520, 490, "square", 2.5);
  s.tone(0.9, 0.8, 0.4, 120, 420, "tri", 1.2);
  s.noise(0.9, 0.8, 0.2, 600, 1400);
  return s.done();
}
function discoverySfx(): Float32Array {
  const s = new Synth(); s.dur(1.6);
  const notes = [523, 659, 784, 1046];
  notes.forEach((n, i) => s.tone(i * 0.14, 0.7, 0.4, n, n * 1.01, "sine", 2.2));
  s.tone(0.56, 1.0, 0.3, 1568, 1560, "sine", 2);
  return s.done(0.8);
}
function scanSfx(): Float32Array {
  const s = new Synth(); s.dur(0.7);
  s.tone(0, 0.5, 0.6, 880, 440, "sine", 3);
  s.tone(0.1, 0.4, 0.3, 1320, 660, "sine", 3.5);
  return s.done(0.7);
}
function liftSfx(): Float32Array {
  const s = new Synth(); s.dur(1.1);
  s.tone(0, 0.9, 0.5, 90, 240, "tri", 1.2);
  s.noise(0, 0.8, 0.25, 500, 1200);
  s.tone(0.85, 0.2, 0.5, 660, 660, "sine", 4);
  return s.done(0.75);
}
function valveSfx(): Float32Array {
  const s = new Synth(); s.dur(1.0);
  s.noise(0, 0.3, 0.6, 700, 300);
  s.tone(0.15, 0.4, 0.5, 180, 120, "square", 4);
  s.noise(0.4, 0.5, 0.5, 300, 900);
  return s.done(0.8);
}
function relicSfx(): Float32Array {
  const s = new Synth(); s.dur(1.2);
  s.tone(0, 0.8, 0.4, 392, 392, "sine", 2);
  s.tone(0.15, 0.8, 0.4, 523, 523, "sine", 2);
  s.tone(0.3, 0.8, 0.35, 659, 660, "tri", 2.2);
  return s.done(0.75);
}
function blueprintSfx(): Float32Array {
  const s = new Synth(); s.dur(1.3);
  const notes = [330, 415, 494, 659];
  notes.forEach((n, i) => s.tone(i * 0.12, 0.6, 0.4, n, n, "tri", 2.5));
  s.noise(0.5, 0.4, 0.2, 2000, 4000);
  return s.done(0.8);
}
function threatWarnSfx(): Float32Array {
  const s = new Synth(); s.dur(0.5);
  s.tone(0, 0.15, 0.6, 233, 220, "square", 5);
  s.tone(0.2, 0.15, 0.6, 233, 220, "square", 5);
  return s.done(0.6);
}
function ambDeep(): Float32Array {
  const s = new Synth(); s.dur(3.0);
  s.tone(0, 2.8, 0.5, 48, 46, "sine", 0.6);
  s.tone(0.4, 2.0, 0.25, 96, 92, "tri", 0.9);
  s.noise(0, 2.6, 0.1, 150, 120);
  return s.done(0.5);
}
function ambMagma(): Float32Array {
  const s = new Synth(); s.dur(3.0);
  s.noise(0, 2.8, 0.4, 400, 900);
  s.tone(0, 2.8, 0.3, 60, 75, "saw", 0.7);
  return s.done(0.5);
}
function ambCrystal(): Float32Array {
  const s = new Synth(); s.dur(3.0);
  s.tone(0, 2.8, 0.25, 880, 884, "sine", 0.5);
  s.tone(0.3, 2.4, 0.2, 1320, 1312, "sine", 0.6);
  s.tone(0.6, 2.0, 0.15, 1760, 1770, "sine", 0.7);
  return s.done(0.45);
}
function stratumSfx(): Float32Array {
  const s = new Synth(); s.dur(2.2);
  s.tone(0, 1.8, 0.5, 65, 130, "sine", 1);
  s.tone(0.2, 1.6, 0.35, 98, 196, "tri", 1.1);
  s.noise(0, 1.6, 0.18, 200, 700);
  s.tone(0.9, 1.2, 0.3, 262, 262, "sine", 1.6);
  return s.done(0.8);
}

// v1.2 new sounds
function gasHiss(): Float32Array {
  const s = new Synth(); s.dur(0.8);
  s.noise(0, 0.7, 0.7, 1800, 3200);
  s.tone(0.05, 0.4, 0.2, 1200, 800, "sine", 6);
  return s.done(0.6);
}
function pressurePop(): Float32Array {
  const s = new Synth(); s.dur(0.5);
  s.tone(0, 0.2, 0.9, 180, 40, "sine", 2);
  s.noise(0, 0.3, 0.8, 600, 200);
  s.noise(0.15, 0.2, 0.5, 1200, 800);
  return s.done(0.85);
}
function steamBurst(): Float32Array {
  const s = new Synth(); s.dur(0.7);
  s.noise(0, 0.5, 0.9, 2400, 1600);
  s.tone(0, 0.3, 0.4, 600, 300, "tri", 5);
  return s.done(0.7);
}
function overheatSfx(): Float32Array {
  const s = new Synth(); s.dur(1.0);
  s.tone(0, 0.3, 0.6, 440, 300, "square", 3);
  s.tone(0.35, 0.3, 0.6, 330, 220, "square", 3);
  s.noise(0, 0.8, 0.4, 2000, 4000);
  return s.done(0.7);
}
function hammerCrack(): Float32Array {
  const s = new Synth(); s.dur(0.4);
  s.tone(0, 0.1, 1.0, 160, 60, "sine", 8);
  s.noise(0, 0.15, 0.9, 1200, 300);
  s.noise(0.12, 0.2, 0.6, 2000, 800);
  return s.done(0.9);
}
function thermalCut(): Float32Array {
  const s = new Synth(); s.dur(0.5);
  s.noise(0, 0.4, 0.8, 1800, 2800);
  s.tone(0, 0.4, 0.5, 300, 600, "saw", 2);
  return s.done(0.75);
}
function rotaryGrind(): Float32Array {
  const s = new Synth(); s.dur(0.45);
  s.tone(0, 0.4, 0.7, 180, 190, "saw", 1);
  s.tone(0, 0.4, 0.4, 360, 380, "square", 1);
  s.noise(0, 0.4, 0.5, 800, 1200);
  return s.done(0.8);
}
function mawBite(): Float32Array {
  const s = new Synth(); s.dur(0.6);
  s.tone(0, 0.3, 1.0, 80, 40, "saw", 2);
  s.tone(0, 0.3, 0.7, 160, 80, "square", 2);
  s.noise(0, 0.4, 0.8, 600, 200);
  s.tone(0.2, 0.3, 0.6, 45, 30, "sine", 1.5);
  return s.done(0.95);
}
function mawShockwave(): Float32Array {
  const s = new Synth(); s.dur(1.2);
  s.tone(0, 0.6, 1.0, 60, 25, "sine", 1.5);
  s.noise(0, 0.8, 0.9, 400, 80);
  s.tone(0.4, 0.5, 0.5, 120, 60, "saw", 2);
  return s.done(0.9);
}
function resonatorPulse(): Float32Array {
  const s = new Synth(); s.dur(0.6);
  s.tone(0, 0.4, 0.6, 880, 880, "sine", 2);
  s.tone(0.05, 0.4, 0.4, 1320, 1320, "sine", 2);
  s.tone(0.1, 0.4, 0.3, 1760, 1760, "sine", 2);
  return s.done(0.7);
}
function breakthroughSfx(): Float32Array {
  const s = new Synth(); s.dur(0.9);
  s.tone(0, 0.2, 0.7, 200, 100, "sine", 4);
  s.noise(0, 0.3, 0.8, 1000, 400);
  s.tone(0.2, 0.6, 0.6, 400, 800, "tri", 1.5);
  s.noise(0.2, 0.5, 0.4, 2000, 3000);
  return s.done(0.85);
}
function tierAcquire(): Float32Array {
  const s = new Synth(); s.dur(1.8);
  s.tone(0, 0.3, 0.5, 262, 523, "tri", 2);
  s.tone(0.25, 0.3, 0.5, 330, 659, "tri", 2);
  s.tone(0.5, 0.3, 0.5, 392, 784, "tri", 2);
  s.tone(0.75, 1.0, 0.6, 523, 1046, "sine", 1.2);
  s.noise(0.75, 0.6, 0.25, 3000, 6000);
  return s.done(0.85);
}
function recoilSfx(): Float32Array {
  const s = new Synth(); s.dur(0.25);
  s.tone(0, 0.15, 0.7, 120, 60, "sine", 5);
  s.noise(0, 0.1, 0.5, 800, 400);
  return s.done(0.6);
}
function landingHeavy(): Float32Array {
  const s = new Synth(); s.dur(0.5);
  s.tone(0, 0.25, 0.9, 80, 40, "sine", 3);
  s.noise(0, 0.3, 0.7, 500, 150);
  return s.done(0.8);
}
function debrisSfx(): Float32Array {
  const s = new Synth(); s.dur(0.35);
  s.noise(0, 0.25, 0.7, 1200, 400);
  s.tone(0, 0.1, 0.3, 300, 150, "tri", 6);
  return s.done(0.6);
}
function magnetStreak(): Float32Array {
  const s = new Synth(); s.dur(0.4);
  s.tone(0, 0.15, 0.5, 600, 900, "tri", 4);
  s.tone(0.12, 0.15, 0.5, 800, 1200, "tri", 4);
  s.tone(0.24, 0.15, 0.5, 1000, 1500, "sine", 4);
  return s.done(0.65);
}
function wowChain(): Float32Array {
  const s = new Synth(); s.dur(1.4);
  s.tone(0, 0.5, 0.8, 150, 60, "sine", 2);
  s.noise(0, 0.6, 0.8, 800, 200);
  s.tone(0.5, 0.8, 0.6, 300, 600, "saw", 1.5);
  s.noise(0.5, 0.7, 0.5, 2000, 800);
  return s.done(0.85);
}
function wowChoir(): Float32Array {
  const s = new Synth(); s.dur(2.0);
  s.tone(0, 1.6, 0.4, 659, 1318, "sine", 0.8);
  s.tone(0.1, 1.6, 0.3, 784, 1568, "sine", 0.9);
  s.tone(0.2, 1.6, 0.25, 1046, 2093, "sine", 1.0);
  s.noise(0, 1.5, 0.15, 4000, 8000);
  return s.done(0.8);
}
function wowBell(): Float32Array {
  const s = new Synth(); s.dur(2.5);
  s.tone(0, 2.0, 0.6, 196, 196, "sine", 0.6);
  s.tone(0, 2.0, 0.3, 294, 294, "sine", 0.7);
  s.tone(0, 2.0, 0.2, 392, 392, "sine", 0.8);
  s.noise(0, 0.3, 0.2, 2000, 4000);
  return s.done(0.75);
}
function wowVault(): Float32Array {
  const s = new Synth(); s.dur(1.5);
  s.tone(0, 0.3, 0.7, 100, 50, "sine", 3);
  s.noise(0, 0.4, 0.7, 800, 200);
  s.tone(0.4, 1.0, 0.6, 400, 800, "tri", 1.2);
  return s.done(0.85);
}
function wowExcavator(): Float32Array {
  const s = new Synth(); s.dur(1.8);
  s.tone(0, 0.5, 0.6, 80, 120, "saw", 1);
  s.tone(0.3, 0.5, 0.5, 120, 180, "square", 1);
  s.tone(0.6, 1.0, 0.5, 200, 300, "sine", 1.2);
  s.noise(0, 1.2, 0.2, 400, 900);
  return s.done(0.8);
}
function wowMaw(): Float32Array {
  const s = new Synth(); s.dur(2.0);
  s.tone(0, 0.8, 1.0, 40, 20, "saw", 1);
  s.noise(0, 1.0, 1.0, 300, 60);
  s.tone(0.8, 1.0, 0.7, 100, 200, "square", 1);
  s.noise(0.8, 1.0, 0.6, 1000, 400);
  return s.done(0.95);
}
function wowFinale(): Float32Array {
  const s = new Synth(); s.dur(3.0);
  s.tone(0, 2.5, 0.5, 110, 110, "sine", 0.5);
  s.tone(0.2, 2.5, 0.4, 165, 165, "tri", 0.6);
  s.tone(0.4, 2.5, 0.3, 220, 220, "sine", 0.7);
  s.tone(0.8, 2.0, 0.35, 330, 330, "sine", 0.8);
  s.noise(0, 2.5, 0.1, 200, 400);
  return s.done(0.7);
}
function ambWater(): Float32Array {
  const s = new Synth(); s.dur(3.0);
  s.noise(0, 2.8, 0.35, 600, 1400);
  s.tone(0, 2.8, 0.15, 120, 115, "sine", 0.6);
  return s.done(0.5);
}
function ambEngine(): Float32Array {
  const s = new Synth(); s.dur(3.0);
  s.tone(0, 2.8, 0.4, 55, 57, "saw", 0.5);
  s.noise(0, 2.8, 0.25, 300, 600);
  s.tone(1.0, 1.0, 0.2, 110, 110, "square", 1);
  return s.done(0.55);
}
function ambBuried(): Float32Array {
  const s = new Synth(); s.dur(3.0);
  s.noise(0, 2.8, 0.2, 200, 500);
  s.tone(0, 2.8, 0.2, 90, 88, "tri", 0.7);
  s.tone(0.5, 2.0, 0.15, 180, 175, "sine", 0.8);
  return s.done(0.5);
}

function toolLoop(kind: string): Float32Array {
  const s = new Synth();
  switch (kind) {
    case "auger":
      s.dur(0.5); s.tone(0, 0.5, 0.5, 210, 230, "saw", 0.5); s.tone(0, 0.5, 0.3, 420, 460, "square", 0.5); s.noise(0, 0.5, 0.2, 900, 1100); return s.done(0.35);
    case "twin":
      s.dur(0.4); s.tone(0, 0.4, 0.55, 300, 340, "saw", 0.5); s.tone(0, 0.4, 0.35, 600, 680, "square", 0.5); s.noise(0, 0.4, 0.3, 1200, 1500); return s.done(0.4);
    case "hammer":
      s.dur(0.5); s.tone(0, 0.12, 0.8, 130, 70, "sine", 6); s.noise(0, 0.1, 0.5, 900, 400); s.tone(0.25, 0.12, 0.8, 130, 70, "sine", 6); s.noise(0.25, 0.1, 0.5, 900, 400); return s.done(0.5);
    case "thermal":
      s.dur(0.6); s.noise(0, 0.6, 0.6, 1600, 2600); s.tone(0, 0.6, 0.3, 90, 110, "saw", 0.6); return s.done(0.42);
    case "seismic":
      s.dur(0.6); s.tone(0, 0.2, 0.6, 60, 50, "sine", 3); s.noise(0, 0.3, 0.4, 400, 200); s.tone(0.3, 0.2, 0.6, 60, 50, "sine", 3); s.noise(0.3, 0.3, 0.4, 400, 200); return s.done(0.5);
    case "rotary":
      s.dur(0.35); s.tone(0, 0.35, 0.7, 160, 175, "saw", 0.5); s.tone(0, 0.35, 0.4, 320, 350, "square", 0.5); s.noise(0, 0.35, 0.45, 700, 1000); return s.done(0.5);
    case "resonator":
      s.dur(0.7); s.tone(0, 0.7, 0.5, 660, 660, "sine", 0.8); s.tone(0, 0.7, 0.35, 990, 1000, "sine", 0.8); s.tone(0, 0.7, 0.2, 1320, 1330, "sine", 0.9); return s.done(0.4);
    case "maw":
      s.dur(0.5); s.tone(0, 0.5, 0.9, 95, 110, "saw", 0.5); s.tone(0, 0.5, 0.6, 190, 220, "square", 0.5); s.noise(0, 0.5, 0.7, 500, 1300); s.tone(0, 0.5, 0.4, 38, 42, "sine", 0.6); return s.done(0.55);
    default: s.dur(0.3); return s.done(0.3);
  }
}

const SOUND_FILES: Record<string, () => Float32Array> = {
  "dig_soft": digSoft, "dig_rock": digRock, "dig_metal": digMetal, "dig_concrete": digConcrete,
  "dig_crystal": digCrystal, "dig_wood": digWood, "dig_heavy": digHeavy, "dig_sand": digSoft,
  "dig_brittle": digRock,
  "hard_fail": hardFail, "upgrade": upgradeSfx, "pickup": pickupSfx, "big_loot": bigLoot,
  "cargo_full": cargoFull, "sell": sellSfx, "explosion": explosion, "ignite": igniteSfx,
  "water": waterSfx, "steam": steamSfx, "magma": magmaSfx, "resonance": resonanceSfx,
  "machine": machineSfx, "base_amb": baseAmb, "hurt": hurtSfx, "extract": extractSfx,
  "discovery": discoverySfx, "stratum": stratumSfx,
  "scan": scanSfx, "lift": liftSfx, "valve": valveSfx, "relic": relicSfx,
  "blueprint": blueprintSfx, "threat_warn": threatWarnSfx,
  "amb_deep": ambDeep, "amb_magma": ambMagma, "amb_crystal": ambCrystal,
  "tool_auger": () => toolLoop("auger"), "tool_twin": () => toolLoop("twin"),
  "tool_hammer": () => toolLoop("hammer"), "tool_thermal": () => toolLoop("thermal"),
  "tool_seismic": () => toolLoop("seismic"), "tool_rotary": () => toolLoop("rotary"),
  "tool_resonator": () => toolLoop("resonator"), "tool_maw": () => toolLoop("maw"),
  // v1.2 new
  "gas_hiss": gasHiss, "pressure_pop": pressurePop, "steam_burst": steamBurst, "overheat": overheatSfx,
  "hammer_crack": hammerCrack, "thermal_cut": thermalCut, "rotary_grind": rotaryGrind,
  "maw_bite": mawBite, "maw_shockwave": mawShockwave, "resonator_pulse": resonatorPulse,
  "breakthrough": breakthroughSfx, "tier_acquire": tierAcquire, "recoil": recoilSfx,
  "landing_heavy": landingHeavy, "debris": debrisSfx, "magnet_streak": magnetStreak,
  "wow_chain": wowChain, "wow_choir": wowChoir, "wow_bell": wowBell, "wow_vault": wowVault,
  "wow_excavator": wowExcavator, "wow_maw": wowMaw, "wow_finale": wowFinale,
  "amb_water": ambWater, "amb_engine": ambEngine, "amb_buried": ambBuried,
};

function main() {
  fs.mkdirSync(OUT, { recursive: true });
  for (const [name, gen] of Object.entries(SOUND_FILES)) {
    const samples = gen();
    fs.writeFileSync(path.join(OUT, name + ".wav"), wav(samples));
  }
  console.log(`generated ${Object.keys(SOUND_FILES).length} sounds → ${OUT}`);
}

main();
